### PR TITLE
Feat/1.28 and fix package repos

### LINKED ISSUE #72: Rockylinux 9 - Failed to download metadata for repo 'kubernetes'
Hi everyone,
I open this ticket because I encountered a problem using the on-prem module in version 1.27.6. Specifically, running the `cluster.yaml` playbook, the "Install Kubernetes dependecies" task fails with the following error:
`'Failed to download metadata for repo ''kubernetes'': Cannot download repomd.xml: Cannot download repodata/repodm.xml: all mirrors were tried'`

By carrying out some checks I saw that the repo used to download the packages seems to be deprecated. I noticed that this issue is already present on this module which could be the case encountered: 

- https://github.com/sighupio/fury-kubernetes-on-premises/issues/63

Below is the environment on which I tested:
- on-prem module tag: 1.27.6
- OS: rockylinux 9
- ansible: 2.10.8
- VM: Virtualbox

As a local resolution, I updated the `yum_repo` and `yum_repo_key` parameters present in the `roles/kube-node-common/vars/main.yml` file, as indicated by the official doc.
- yum_repo: "https://pkgs.k8s.io/core:/stable:/v1.27/rpm/"
- yum_repo_key: "https://pkgs.k8s.io/core:/stable:/v1.27/rpm/repodata/repomd.xml.key"

### PR DESCRIPTION
**Pull request by nutellinoit**
Tested all versions with Debian VMs and with Rocky VMs

fixes #72, #63

### CODE REVIEW

**Review by ralgozino — APPROVED** [review]
LGTM

**Review by stefanoghinelli — COMMENTED** [review]
LGTM!

Just a small hint, we could add the new release version also in the examples

https://github.com/sighupio/fury-kubernetes-on-premises/blob/98fe99d20cb25882bf8397c09cfb9a14717ad3a1/examples/playbooks/hosts.yaml#L64

**Comment by ralgozino** [comment]
updated example hosts.yaml

**Review by ralgozino — APPROVED** [review]

**Review by stefanoghinelli — APPROVED** [review]

**Review by sbruzzese902 — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
